### ISSUE TITLE
Move /welcome applinks from properties to UAS request

### ISSUE THREAD

**Issue by totto** [Cantara/Whydah-SSOLoginWebApp#10]

**Comment by baardl** [comment]
Not sure about what you want us to create here.

B.

**Comment by totto** [comment]
In the /welcome page of SSOLWA, we have a list of application a user has access to, if the applications have an URL, the application is linked and clickable.  Today the applicationname->URL is resolved in the appLinks property of ssolwa as a json list object. This should be updated tu ask UAS and read the link form the new Application model which have this property as an administered peoperty

**Comment by baardl** [comment]
Perfect! :)

**Comment by totto** [comment]
Data is now available, just need som javascript adjustments in the frontend to use the new data structure
