### ISSUE TITLE
Problems setting new password based on "forgot password" email

### ISSUE THREAD

**Issue by StigLau** [Cantara/Whydah-SSOLoginWebApp#20]
Went to sso/login -> Forgot Password. Change password email received
went to "New Password" 
Typed in new password  and pressed "change password"

Expectation: Could insert new, normal length password.

Result: 14:23 18.05.2016
HTTP ERROR 500
Problem accessing /useradminservice/a9ec3eee81f53e8e0edc88d83deeb3b3/auth/password/reset/username/stisse/newpassword/c3Rpc3NlOjE0NjM4MzMwMjg1NTQ6QkVvUU1sdEVLQlozSmpNYURVaDJNd1V2SmlOMU1GY05ieWNSUHdvVllYd3FMUk53ZFEwQkFIVTJJREVtUEcxN0tUaC9mdz09. Reason:

    Request failed.
Powered by Jetty:// 9.3.z-SNAPSHOT
username:stisse

Note: old password still functional.

**Comment by totto** [comment]
N/A - was "dead" whydah installation

**Comment by StigLau** [comment]
Still same problem

**Comment by StigLau** [comment]
Detailing of performed actions:
 * Create new user -> https://whydahdev.cantara.no/sso/signup
 * Receive reset-password email -> set password -> log in -> log out
 * Reset password -> https://whydahdev.cantara.no/sso/resetpassword
 * Receive reset-password email -> Enter new valid password -> submit -> *BAM* HTTP500

**Comment by totto** [comment]
Hmm...  I still can't reproduce...   Is it a data-issue with your username or possibly a blacklisted password?
